spring.application.name=Vellox
server.port=8100

# ===============================
# Database configuration
# ===============================

spring.datasource.url=jdbc:postgresql://localhost:5432/chat_app_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# ===============================
# JPA / Hibernate configuration
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# Spring Mail Configuration
# ===============================

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

# Advanced SMTP Properties
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===============================
# JWT Configuration
# ===============================

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# ===============================
# Google OAuth2 Configuration
# ===============================

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

spring.security.oauth2.client.registration.google.scope[0]=email
spring.security.oauth2.client.registration.google.scope[1]=profile

# ===============================
# GitHub OAuth2 Configuration
# ===============================

spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}

spring.security.oauth2.client.registration.github.scope[0]=user:email
spring.security.oauth2.client.registration.github.scope[1]=read:user